FROM node:20-alpine AS build
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY index.html ./index.html
COPY vite.config.ts ./vite.config.ts
COPY .env.production ./.env.production
COPY src ./src
RUN npm run build

FROM nginx:1.27-alpine AS runtime
COPY nginx.frontend.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
